name: Publish Images

on:
  push:
    branches:
      - 'develop'
      - 'main'
    tags:
      - 'v*.*.*'
    paths:
      - 'services/**'
      - 'postman_collections/**'
      - 'deploy/**'
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PLATFORMS: "linux/amd64,linux/arm64"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set lowercase repository name
        run: |
          REPO_LC="${{ github.repository == '' && 'unknown' || github.repository }}"
          echo "REPO_LC=$(echo "$REPO_LC" | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_ENV"

      - name: Get branch/tag info
        id: branch-name
        uses: tj-actions/branch-names@v8
        with:
          strip_tag_prefix: 'v'

      - name: Set TAG_NAME and TAG_LATEST
        run: |
          if [ "${{ steps.branch-name.outputs.is_tag }}" = "true" ]; then
            echo "TAG_NAME=${{ steps.branch-name.outputs.tag }}" >> "$GITHUB_ENV"
            echo "TAG_LATEST=${{ steps.branch-name.outputs.tag }}" >> "$GITHUB_ENV"
          elif [ "${{ github.ref_name }}" = "main" ]; then
            echo "TAG_NAME=main" >> "$GITHUB_ENV"
            echo "TAG_LATEST=latest" >> "$GITHUB_ENV"
          else
            echo "TAG_NAME=${{ github.ref_name }}" >> "$GITHUB_ENV"
            echo "TAG_LATEST=${{ github.ref_name }}" >> "$GITHUB_ENV"
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push crapi-identity
        uses: docker/build-push-action@v3
        with:
          context: ./services/identity
          tags: |
            ghcr.io/${{ env.REPO_LC }}/crapi-identity:${{ env.TAG_LATEST }}
            ghcr.io/${{ env.REPO_LC }}/crapi-identity:${{ env.TAG_NAME }}
          platforms: ${{ env.PLATFORMS }}
          push: true
          cache-from: type=gha,scope=identity-service
          cache-to: type=gha,mode=max,scope=identity-service

      - name: Build and push crapi-workshop
        uses: docker/build-push-action@v3
        with:
          context: ./services/workshop
          tags: |
            ghcr.io/${{ env.REPO_LC }}/crapi-workshop:${{ env.TAG_LATEST }}
            ghcr.io/${{ env.REPO_LC }}/crapi-workshop:${{ env.TAG_NAME }}
          platforms: ${{ env.PLATFORMS }}
          push: true
          cache-from: type=gha,scope=workshop-service
          cache-to: type=gha,mode=max,scope=workshop-service

      - name: Build and push crapi-chatbot
        uses: docker/build-push-action@v3
        with:
          context: ./services/chatbot
          tags: |
            ghcr.io/${{ env.REPO_LC }}/crapi-chatbot:${{ env.TAG_LATEST }}
            ghcr.io/${{ env.REPO_LC }}/crapi-chatbot:${{ env.TAG_NAME }}
          platforms: ${{ env.PLATFORMS }}
          push: true
          cache-from: type=gha,scope=chatbot-service
          cache-to: type=gha,mode=max,scope=chatbot-service

      - name: Build and push crapi-community
        uses: docker/build-push-action@v3
        with:
          context: ./services/community
          tags: |
            ghcr.io/${{ env.REPO_LC }}/crapi-community:${{ env.TAG_LATEST }}
            ghcr.io/${{ env.REPO_LC }}/crapi-community:${{ env.TAG_NAME }}
          platforms: ${{ env.PLATFORMS }}
          push: true
          cache-from: type=gha,scope=community-service
          cache-to: type=gha,mode=max,scope=community-service

      - name: Build and push crapi-web
        uses: docker/build-push-action@v3
        with:
          context: ./services/web
          tags: |
            ghcr.io/${{ env.REPO_LC }}/crapi-web:${{ env.TAG_LATEST }}
            ghcr.io/${{ env.REPO_LC }}/crapi-web:${{ env.TAG_NAME }}
          platforms: ${{ env.PLATFORMS }}
          push: true
          cache-from: type=gha,scope=web-service
          cache-to: type=gha,mode=max,scope=web-service

      - name: Build and push gateway-service
        uses: docker/build-push-action@v3
        with:
          context: ./services/gateway-service
          tags: |
            ghcr.io/${{ env.REPO_LC }}/gateway-service:${{ env.TAG_LATEST }}
            ghcr.io/${{ env.REPO_LC }}/gateway-service:${{ env.TAG_NAME }}
          platforms: ${{ env.PLATFORMS }}
          push: true
          cache-from: type=gha,scope=gateway-service
          cache-to: type=gha,mode=max,scope=gateway-service

      - name: Build and push mailhog
        uses: docker/build-push-action@v3
        with:
          context: ./services/mailhog
          tags: |
            ghcr.io/${{ env.REPO_LC }}/mailhog:${{ env.TAG_LATEST }}
            ghcr.io/${{ env.REPO_LC }}/mailhog:${{ env.TAG_NAME }}
          platforms: ${{ env.PLATFORMS }}
          push: true
          cache-from: type=gha,scope=mailhog-service
          cache-to: type=gha,mode=max,scope=mailhog-service
